server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true   # ✅ new property name
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**

            - id: research-paper-service
              uri: lb://research-paper-service
              predicates:
                - Path=/api/research-paper/**
            - id: search-service
              uri: lb://search-service
              predicates:
                - Path=/api/search/**


# Shared JWT configuration (use the same Base64-encoded secret as userManagementService)
security:
  jwt:
    secret: UkFOVHJhdkluZVRlbXBlcnlCb2R5c0NvdWx0Wk1hcmFSVE1hY2tIb2RzdHJhbUE=

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
