server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true   # ✅ modern property
      # optional: route filters if you want custom paths
      routes:
        - id: author-service
          uri: lb://author-service   # lb = load-balanced from Eureka
          predicates:
            - Path=/authors/**

        - id: researchpaper-service
          uri: lb://researchpaper-service
          predicates:
            - Path=/papers/**

        - id: university-service
          uri: lb://university-service
          predicates:
            - Path=/universities/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
