server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # Eureka server doesn’t register with itself
    fetch-registry: false
  server:
    enable-self-preservation: false  # For development only
