spring:
  application:
    name: research-paper-service
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/api/auth/.well-known/jwks.json

  datasource:
    url: jdbc:postgresql://localhost:5432/libreresearchhub_researchpaper_service
    username: libreresearchhub
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8091

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

user:
  service:
    url: http://localhost:8090/
    token: UkFOVHJhdkluZVRlbXBlcnlCb2R5c0NvdWx0Wk1hcmFSVE1hY2tIb2RzdHJhbUE=

search:
  service:
    url: http://localhost:8097/
    token: UkFOVHJhdkluZVRlbXBlcnlCb2R5c0NvdWx0Wk1hcmFSVE1hY2tIb2RzdHJhbUE=


security:
  jwtSecret: UkFOVHJhdkluZVRlbXBlcnlCb2R5c0NvdWx0Wk1hcmFSVE1hY2tIb2RzdHJhbUE=

spring.data.redis.repositories.enabled: false


