server:
  port: 8090

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/yeadkhail
    driver-class-name: org.postgresql.Driver
    username: yeadkhail
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

security:
  jwtSecret: UkFOVHJhdkluZVRlbXBlcnlCb2R5c0NvdWx0Wk1hcmFSVE1hY2tIb2RzdHJhbUE=
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 604800000

logging:
  level:
    com.ssm.webarch.config: DEBUG
    com.ssm.webarch.auth: DEBUG
    org.springframework.security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
