server:
  port: 8090

spring:
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    driver-class-name: org.postgresql.Driver
    username: yeadkhail
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  jwtSecret: UkFOVHJhdkluZVRlbXBlcnlCb2R5c0NvdWx0Wk1hcmFSVE1hY2tIb2RzdHJhbUE=
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 604800000

logging:
  level:
    com.ssm.webarch.config: DEBUG
    com.ssm.webarch.auth: DEBUG
    org.springframework.security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

search:
  service:
    url: http://localhost:8097/

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


spring.data.redis.repositories.enabled: false